# Generated by Django 5.2.3 on 2025-06-27 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencystaff',
            name='branch',
            field=models.ManyToManyField(related_name='agency_branch', to='business.branch'),
        ),
        migrations.AddField(
            model_name='agencystaff',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_staff_business', to='business.business'),
        ),
        migrations.AddField(
            model_name='agencystaff',
            name='marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_staff_marketing', to='business.marketing'),
        ),
        migrations.AddField(
            model_name='agencystaff',
            name='new_assigned',
            field=models.ManyToManyField(related_name='new_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencystaff',
            name='staff',
            field=models.ManyToManyField(related_name='agency_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.branch'),
        ),
    ]
